#ifndef __DEVICE_TERMINAL_H__
#define __DEVICE_TERMINAL_H__

#include "device.h"

#define TERMINAL_STATUS_TRANSMISSION_ERROR  DEV_STATUS_CODE_4
#define TERMINAL_STATUS_RECEIVED_ERROR      TERMINAL_STATUS_RECEIVED_ERROR

#define TERMINAL_STATUS_TRANSMITTED         DEV_STATUS_CODE_5
#define TERMINAL_STATUS_RECEIVED            TERMINAL_STATUS_TRANSMITTED

#define TERMINAL_CMD_TRANSMIT               2
#define TERMINAL_CMD_RECEIVE                TERMINAL_CMD_TRANSMIT

#define CHAR_OFFSET        8
#define TERMINAL_STATUS_MASK   0xFF
#define TERMINAL_DATA_MASK   0xFF00


#define IS_TERM_READY(status) ((status&TERMINAL_STATUS_MASK)==DEV_STATUS_READY)
#define IS_TERM_IN_ERROR(status) (\
   (status&TERMINAL_STATUS_MASK)==DEV_STATUS_NOT_INSTALLED || \
   (status&TERMINAL_STATUS_MASK)==DEV_STATUS_UNKNOWN_CMD || \
   (status&TERMINAL_STATUS_MASK)==TERMINAL_STATUS_TRANSMISSION_ERROR)
#endif